services:
  postgresql:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bora_de_excursao
    ports:
      - "5432:5432"
    networks:
      - nw-bora-de-excursao
    restart: unless-stopped
    volumes:
      - ./script:/docker-entrypoint-initdb.d
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - LOCALSTACK_HOST=localhost
      - SERVICES=s3
      - DEBUG=${DEBUG:-0}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - nw-bora-de-excursao
networks:
  nw-bora-de-excursao:
    driver: bridge